### ISSUE TITLE
Memory leak in dart:ffi samples

### ISSUE THREAD

**Issue by xzfc** [dart-lang/samples#93]
Here the memory is allocated in `reverse()`:
https://github.com/dart-lang/samples/blob/21e809c882ee79837d49b6d79773b6ae918c21c0/ffi/structs/structs_library/structs.c#L31

Here it used in `toDartString()`:
https://github.com/dart-lang/samples/blob/21e809c882ee79837d49b6d79773b6ae918c21c0/ffi/structs/structs.dart#L67-L68

It is not clear how the allocated memory should be freed.

Should it be done using [`malloc.free()`](https://api.dart.dev/stable/2.12.1/dart-ffi/Allocator/free.html) call or there is a more conventional way to do it in dart? OTOH, if `toDartString()` actually takes ownership for this C string and there is no memory leak, then this behavior should be documented somewhere.

**Comment by dcharkes** [comment]
The snippet actually contains two memory leaks, `backwards.toNativeUtf8()` also leaks. 

https://github.com/dart-lang/samples/blob/21e809c882ee79837d49b6d79773b6ae918c21c0/ffi/structs/structs.dart#L65-L69

should be

```dart
  final reverse = dylib.lookupFunction<reverse_native, Reverse>('reverse');
  final backwards = 'backwards'.toNativeUtf8();
  final reversedMessage =
      reverse(backwards, backwards.length).toDartString();
  malloc.free(backwards);
  print('$backwards reversed is $reversedMessage');
  malloc.free(reversedMessage);
```

However, this is slightly ugly, because now Dart is calling `free` on a `malloc` in C.

It would be cleaner to add a `void free_string(char* str)` to C which does the `free`ing and invoke that from Dart instead of `malloc.free(reversedMessage)`. That way you are sure that `malloc` and `free` match up from the same compilation unit (which can be a problem on Windows - you cannot use `free` from one dll on a `malloc`ed pointer from another dll).

**Comment by xzfc** [comment]
Thanks. I think it would make sense to cover this in the sample code since memory management is a common issue with ffi code.
